### PR TITLE
Save user preferences

### PR DESCRIPTION
**Pull request by JohnParks032**
Fixes Issue https://github.com/ChrispyPeaches/FocusFriends/issues/53

## Problem
As a user, I can have my settings saved and reloaded when I open the app

### Definition of Done
- The user has access to a feature rich setting menu
- Default settings are added and saved to .NET MAUI preferences 
- Settings can be saved according to the changed made by the user

## Solution
- Implement .NET MAUI Preferences
- Remove pre-existing bool values in settings
- Removed old unused settings (Dark Mode, Languages, SFX)
- Added settings to be used (Toggle Tips, Toggle Ratings)
- Replace button and sliders to adjust preference values saved in Key/Value pairs
- Adjusted look and design as well

## Documentation
An example of a Key/Value Pair for saving ambient audio

image

.Get is used to check if there is saved value, and if there isn't, the second value is the "Default value"

When changing the preference, .Set is used:

image

For switches, the name of the switch is passed through a function where a key and value is set.

image

## How was this tested?
- App was ran and then settings were adjusted
- After closing and reopening the app, the settings adjustments were left the same

### CODE REVIEW

**Comment by iggy808** [comment]
LGTM!

**Review by iggy808 — DISMISSED** [review]

**Review by ChrispyPeaches — CHANGES_REQUESTED** [review]
This looks really good and I love the modularity!

I do have a couple suggestions:
1. Do you think it would make sense to have an enum or something representing the keys for each entry so it could be easier to access the settings around the app?
    - For example: 
        ```
        public enum SettingsKeys
       {
            AmbianceVolume,
            NotificationsEnabled 
            ... 
        }
        ```
2. Could we have the default values created on app startup if they don't exist? In the current implementation, if a preference is requested before the user goes to the SettingsPage, the preferences don't exist.

**Review by ChrispyPeaches — APPROVED** [review]
LGTM!

**Review by iggy808 — APPROVED** [review]
LGTM!

**Pull request merged**
