### PR TITLE
[HOTFIX] User profile selected item fixes / Adjust styling / Connect selected item buttons to correct pages

### PR DESCRIPTION
**Pull request by iggy808**
Fixes user selected item labels not appropriately displaying

- Leaderboards page refactoring and modification to show loading spinner
- Fixed issue in user login when a auth0 request fails and an id is not added to a user in the local context
- Removed decor given to user when continuing without login
- Added generic and async overloads to popup service
- Removed logged in check on user badges page
- Restricted username size to 14
- Reworked pronoun field validation to allow a user to remove pronouns
- Adjusted size of badge image on user profile page

### CODE REVIEW

**Review by wesleypayton — DISMISSED** [review]
Nice fixes guys! Good work! 💸

**Review by wesleypayton — APPROVED** [review]
LGTM!

**Comment by JohnParks032** [comment]
Looks good! Thanks for the important hotfixes

**Review by JohnParks032 — APPROVED** [review]
Looks good! Thanks for the important hotfixes

**Pull request merged**
