### PR TITLE
Add continuous deployment

### LINKED ISSUE #4: Setup CI/CD Flow
As a developer, I need a CI/CD flow for deployment and testing

## Subtasks
- [x] Get Familiar with Github Actions
- [x] Documentation
- [x] Testing

#### CI
- [x] Setup build status checks for FocusAPI and FocusApp
- [x] Setup a flow for verifying the apps builds when reviewing pull requests

#### CD
- [x] Get Familiar with Docker & Portainer
- [x] Setup a flow for deploying the API to a test environment

### PR DESCRIPTION
**Pull request by ChrispyPeaches**
Fixes #4

## Problem

As a user, I would like to be able to look at the variety of shop content on the shop page.
As a developer, I would like to implement the backend necessary to populate the shop carousels.

## Solution
    
- Adding Deployment Ability
    - Added a Docker Compose file which provides instructions for creating a docker stack
    - Modified the FocusAPI DockerFile to work with solution file structure (projects being moved into `src/{Project Name}`
    - Added a `deploy` Github Action 
- FocusApi Project changes
    - Allowed swagger pages to be shown on TEST environment by disabling them for only on production instead of only allowing them in the development environment
    - Setup the FocusApi database to be created on program start if it doesn't already exist
    - Moved the database connection string to the appsettings files
        - Note for the TEST deployment, for security reasons, the connection string is added manually as environment variables instead of committing it to the repo

## Documentation
- added to [tech stack](https://github.com/ChrispyPeaches/FocusFriends/wiki)
- Added some starting docs for the [test environment](https://github.com/ChrispyPeaches/FocusFriends/wiki/Test-Environment)
- The CD flow was previously documented in the [Gitflow section of the processes document](https://github.com/ChrispyPeaches/FocusFriends/wiki/Standards-&-Processes#gitflow)

## How did you test this?
1. Verified deployment was successful the the API at the following address
    - http://test.zenpxl.com:25565/swagger/index.html
2. Verified I was able to connect to the deployed database and that it had the proper schema using a SQL connection client such as SSMS or DataGrip
    - Verifying that it has the proper schema shows that the project was able to connect to the database and create the tables
    - The address to connect to it is at test.zenpxl.com:8002
3. Verified that the `deploy` Github Action runs only on a push to the `test` branch

### CODE REVIEW

**Review by iggy808 — DISMISSED** [review]
Slick slick slick- LGTM!! I'd like a walkthrough of how this works sometime! Looks very good and professional

**Comment by ChrispyPeaches** [comment]
@iggy808 
Yeah absolutely! I plan on improving the docs in the future too!

**Review by JohnParks032 — APPROVED** [review]
LGTM pt. 2

**Review by wesleypayton — APPROVED** [review]
Awesome work! Thanks for putting this together

**Pull request merged**
