### PR TITLE
Add IslandDisplayView / Update CurrentUser / Update User backend / Update login backend / Add InitialDataSync / Improvements & Cleanup

### LINKED ISSUE #67: Add custom control for displaying the island
## Problem
As a developer, I need to have a custom control for showing my island that I can use on multiple pages and that can show the currently selected pet, decor, etc.

## Definition of Done
- Currently selected pet, decor, badge, and decor is stored in authentication service, mobile db, and API db 
- Custom control is usable anywhere in the application
- Custom control is usable if user is not logged in

## Subtasks
- [x] Extract island page into a custom control
- [x] Setup backend to attach pet and island to new users
- [x] Create columns in db for user selected pet, sound, etc.
- [x] Add display decor to island
- [x] Include the selected pet, and decor in the displayed island
- [x] Setup sync to grab initial pet and island if they don't exist in the database
- [x] Make display of pet on island more dynamic
- [ ] Documentation and testing

### PR DESCRIPTION
**Pull request by ChrispyPeaches**
Fixes #67

## Problem

As a developer, I need to have a custom control for showing my island that I can use on multiple pages and that can show the currently selected pet, decor, etc.

To achieve this other areas of the applications needed to provide accommodations to ensure there was always a pet, island, and decor item to display and that the instance of those that the user currently has selected is shown.

### Definition of Done

- Currently selected pet, decor, badge, and decor is stored in authentication service, mobile db, and API db
- Custom control is usable anywhere in the application
- Custom control is usable if user is not logged in

#### Application-Wide

- Added a ResultWrapper for communicating status codes between API controllers and API MediatR features
- Added a Consts file in FocusCore to detail the names of the default items to ensure consistency between retrieved default items in FocusAPI and FocusApp
- SyncInitialData feature
  - The FocusApp will count the entries in the Islands, Pets, and Furniture tables. For each table that has 0 entries, a default item for that table will be retrieved from the API.
  - The decor item/furniture is included in this sync for testing purposes, in the final product, a user won't get a decor item by default
  - This process runs on startup of the FocusApp
- Database
  - Added the Islands and UserIslands tables and database models to the FocusAPI and FocusApp databases
  - Added the `HeightRequest` field to the Pets and Furniture/Decor tables

#### API

- Sync

  - Added SyncInitialData endpoint and feature
  - Added a SyncService helper

    - Currently it only serves to provide shared logic between two MedatR features to get the default island and pet
- User

  - Modified GetUser endpoint and feature
    - Extracted the create user functionality from this feature and placed it in a CreateUser feature and endpoint for separation of concerns and GET protocol compliance
  - Implemented CreateUser endpoint and feature

#### App

- AuthenticationService
  - Changed the CurrentUser property in the Authentication service from BaseUser to User to match the user type pulled from the database.
  - Added property changed notification for the CurrentUser to the AuthenticationService.
    - Added the ability to bind to the CurrentUser instance's selected island, pet, badge, and decor item
- Added a GetDefaultItems MediatR feature
  - Retrieves the default pet, island, and a decor item (decor item is also tempoarary here for testing) by name from the local database
  - This assumes that the startup process for fetching the default pet, island, and decor item has successfully completed. It does have error handling in place for if it wasn't successful.
- Modified the GetUserLogin MediatR feature
  - Updated to work with changes to GetUserByoAuthId API endpoint and the CreateUser endpoint
  - Updated to ensure the user's selected pet, island, and decor are updated
- Added IslandDisplayView
  - All details in documentation linked here
- Modified LoginPage
  - To assign the selected pet, island, and decor item for the current user or create an "empty" user (one that only holds data about selected items)
- Modified check to show EnsureLoginPopup on ShopPage and SocialPage to work with changes to CurrentUser and the usage of an "empty" user
- Modified TimerPage to accomodate IslandDisplayView and to bind the CurrentUser's selected items to the view

### Improvements

- Added ProjectionHelpers to the API and app to allow for easy projection between base and derived versions of the database models
- Added instantiation for all collections in the Users table
- Moved the FocusAPI MediatR regsitration into its own method and modified it to automatically grab all features and validators automatically
  - This was modified because when creating a new mediatr feature I'd needed to manually register it

### Bug fixes and Cleanup

- Cleaned up namespace inconsistencies (Some used `FocusApi`, others used `FocusAPI`, they now all use `FocusAPI`)
- Fixed bug with the SyncMindfulnessTips query where an empty list would be rejected
- Fixed issue with API FocusContext database creation logic not working with migrations
- Added regions to the IAPIClient to separate by API controller
- Cleaned up refences and warnings in MauiProgram and TimerPage
- Removed Sharpnado Tabs
- Removed abstract modifiers from some database models which did not allow them to be instantiated

## Documentation

- [MediatrResultWrapper](https://github.com/ChrispyPeaches/FocusFriends/wiki/MediatR-Result-Wrapper)
- [Updated DB Base Schema diagram](https://github.com/ChrispyPeaches/FocusFriends/wiki/Database-Design#eer-diagram)
- [IslandDisplayView](https://github.com/ChrispyPeaches/FocusFriends/wiki/IslandDisplayView-Custom-Control)
- [User Login flow](https://github.com/ChrispyPeaches/FocusFriends/wiki/User-Authentication#focusfriends-backend-implementation)

## Additional Information
Heres some SQL scripts and an explanation of the files
### Details about file sent below
Unmodified Scripts (from the ones Evan made)
- dbo.Sounds.Table.sql

Modified Scripts (from the one's Evan made)
- Add-Pets-Filler-Data -  I added the "Cool Cat" (since the user creation & skip login logic look for that speific one)
    - It also includes the pets HeightRequests so that the UI knows how big to make them. The default is 0 without the script so they wouldn't show up if you didn't run it
- Add-Furniture-Filler-Data - I don't think anything changed besides cropping that one hyperrealistic table image

New/Added Scripts
- Add-Initial(Default)-Island - Adds the initial/default island to the database
- Add-Initial(Default)-Pet - Adds the initial/default pet to the database
[Database_Filling_SQL_Scripts.zip](https://github.com/ChrispyPeaches/FocusFriends/files/14858505/Database_Filling_SQL_Scripts.zip)

## How was this tested?
**Todo**

### CODE REVIEW

**Comment by ChrispyPeaches** [comment]
Fixed cruical timer bug

**Review by JohnParks032 — DISMISSED** [review]
Yippie! LGTM. Approved. 💯 

Thank you fro the timer fix too!

**Review by JohnParks032 — APPROVED** [review]
Approved!

**Review by iggy808 — APPROVED** [review]
KILLT IT

**Pull request merged**
