### PR TITLE
Implement daily and weekly leaderboards

### LINKED ISSUE #66: Implement Leaderboard Backend/Frontend
## Problem
As a user, I would like to see a leaderboard of my friend's study session stats. Additionally, I would like to be able to view these stats within a daily or weekly timeframe.

## Definition of Done
I can navigate to the leaderboards screen, and I can view daily/weekly leaderboards of my friends' stats.

## Subtasks
- [ ] Create UI buttons for Daily / Weekly leaderboards
- [ ] Create UI for showing top 3 friends on the leaderboard
- [ ] Create UI for scrolling through friends that are not in the top 3
- [ ] Create API endpoint for fetching Daily friend session stats
- [ ] Create DTO that includes friend data as well as aggregated session data
- [ ] On the server, aggregate daily friend session stats, and return DTO for friend / their aggregated session stats
- [ ] On Daily leaderboard page load, call Daily friend session stats endpoint for leaderboard data
- [ ] Populate UI with friend session stats
- [ ] Create API endpoint for fetching Weekly friend session stats
- [ ] On the server, aggregate weekly friend session stats, and return DTO for friend / their aggregated session stats
- [ ] On Weekly leaderboard page load, call Weekly friend session stats endpoint for leaderboard data

### PR DESCRIPTION
**Pull request by iggy808**
Fixes #66 

## Problem
Needed daily and weekly leaderboards to compete with friends.

### Definition of Done
I can navigate to the leaderboards screen, and I can view daily/weekly leaderboards of my friends' stats.

## Solution
- [x] Create UI buttons for Daily / Weekly leaderboards
- [x] Create UI for showing top 3 friends on the leaderboard
- [x] Create UI for scrolling through friends that are not in the top 3
- [x] Create API endpoint for fetching Daily friend session stats
- [x] Create DTO that includes friend data as well as aggregated session data
- [x] On the server, aggregate daily friend session stats, and return DTO for friend / their aggregated session stats
- [x] On Daily leaderboard page load, call Daily friend session stats endpoint for leaderboard data
- [x] Populate UI with friend session stats
- [x] Create API endpoint for fetching Weekly friend session stats
- [x] On the server, aggregate weekly friend session stats, and return DTO for friend / their aggregated session stats
- [x] On Weekly leaderboard page load, call Weekly friend session stats endpoint for leaderboard data

## Documentation
WIP

## How was this tested?
Manually. Generated test data using the scripts below. Note: The user ids / friends relations will need to be established to match your local db.

[TestDailySessionLeaderboardsql.txt](https://github.com/ChrispyPeaches/FocusFriends/files/14912377/TestDailySessionLeaderboardsql.txt)

### CODE REVIEW

**Comment by ChrispyPeaches** [comment]
For easier testing, I modified the sql script attached to add the users, friendships, and user sessions:

[AddUsersFriendshipsAndSession.txt](https://github.com/ChrispyPeaches/FocusFriends/files/14913563/AddUsersFriendshipsAndSession.txt)

**Review by ChrispyPeaches — CHANGES_REQUESTED** [review]
Looks amazing, nice work! Especially the queries, they were very clean!

Left a small note, but other than thank amazing stuff, keep it up!!

**Review by ChrispyPeaches — APPROVED** [review]
Perfect!

**Review by JohnParks032 — APPROVED** [review]
LGTM!

**Pull request merged**
